title: Pedro Mello
description: >-
  Personal site of Pedro Mello.
baseurl: ""
url: "https://www.pedromello.uk"

author_name: Pedro Mello
email: contactme@pedromello.uk
github_url: https://github.com/pedromellogomes
linkedin_url: https://linkedin.com/in/pedromellogomes

author:
  name: Pedro Mello
  email: contactme@pedromello.uk

social:
  name: Pedro Mello
  links:
    - https://github.com/pedromellogomes
    - https://linkedin.com/in/pedromellogomes

lang: en_GB

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - CLAUDE.md
